### ISSUE TITLE
Diarizing WAV file: ValueError: Input must be 1- or 2-d.

### ISSUE THREAD

**Issue by Compy** [egonina/pycasp#1]
I am using pycasp with CUDA 5.0 on Ubuntu 12.04LTS (GeForce GTX 650). I am trying to test out pycasp using the Diarizer example by diarizing a 65 minute 16 bit, 8khz wav file.

First, I try to convert the wav to htk, I create a config.mfcc:

SOURCEKIND = WAVEFORM
SOURCEFORMAT = WAVE
SOURCERATE = 625
TARGETKIND = MFCC_0
TARGETRATE = 100000.0
WINDOWSIZE = 250000.0
USEHAMMING = T
PREEMCOEF = 0.97
NUMCHANS = 20
CEPLIFTER = 22
NUMCEPS = 12

Then i run:
HCopy -C config.mfcc test.wav test.htk
This completes successfully.

I then set diarizer.cfg as follows: 

[Diarizer]
basename = IS1008a
mfcc_feats = /home/jltest/test.htk
output_cluster = /home/jltest/test.rttm
gmm_output = IS.gmm

em_iterations = 3
initial_clusters = 16
M_mfcc = 5

KL_ntop = 3
num_seg_iters_init = 1
num_seg_iters = 1
seg_length = 250

After running python cluster.py, I get:

 size of each cluster: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10]
 size of each cluster: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 10]
 size of each cluster: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 10, 10]
 size of each cluster: [5, 5, 5, 5, 5, 5, 5, 5, 10, 10, 10, 10]
 size of each cluster: [5, 5, 5, 5, 5, 5, 5, 10, 10, 10, 15]
 size of each cluster: [5, 5, 5, 5, 5, 10, 10, 10, 15, 10]
 size of each cluster: [5, 5, 5, 5, 10, 10, 15, 10, 15]
 size of each cluster: [5, 5, 5, 10, 10, 15, 10, 20]
 size of each cluster: [5, 5, 5, 10, 10, 20, 25]
 size of each cluster: [5, 5, 5, 20, 25, 20]
 size of each cluster: [5, 5, 20, 25, 25]
 size of each cluster: [5, 20, 25, 30]
 size of each cluster: [20, 30, 30]
 size of each cluster: [30, 50]
 size of each cluster: [80]
=== Total clustering time:  85.4342420101
=== Final size of each cluster: [80]
...Writing out RTTM file...
DONE writing RTTM file
Traceback (most recent call last):
  File "cluster.py", line 707, in <module>
    diarizer.write_to_GMM(gmmfile)
  File "cluster.py", line 203, in write_to_GMM
    g_covar = np.diag(g_covar_full)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/twodim_base.py", line 292, in diag
    raise ValueError("Input must be 1- or 2-d.")
ValueError: Input must be 1- or 2-d.

The file IS.gmm is created with the following:

Number of clusters: 1
Cluster 0
Number of Gaussians: 80

Any ideas on the issue I'm running into? I was hoping to get the RTTM cluster file.

Thank you!

**Comment by Compy** [comment]
Correction, the RTTM cluster file is created, but not for the entire length of the recording, and I think that error is cutting things off early in the process. It gets about 2/3rds through.

**Comment by MilesWen** [comment]
Hi I encountered exactly the same issue like you. How did you solve it?

**Comment by terryyizhong** [comment]
Same problem, any solution?
